---
name: Syndication-ESF
version: 0.1
author:
  - Brian Cassidy <bricas@cpan.org>
abstract: Create and update ESF files
license: perl
provides:
  Syndication::ESF:
    file: lib/Syndication/ESF.pm
    version: 0.1
generated_by: Module::Build version 0.2612
